# H2
spring:

#DataSource
  datasource:
    url: jdbc:mysql://localhost:3306/loja
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl_auto: update
      properties:
        hibernate:
          format_sql: true
jwt:
  secret: secreto