# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2

#DataSource
  datasource:
    url: jdbc:h2:file:/Users/lucasvinicius/BD/BD
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl_auto: update
      properties:
        hibernate.format_sql: true